<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Name</name>
  <uuid>8ad9c324-f57f-48a6-939c-fa5281121f5f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ for each item ,  in  the items  of 'my shopping' print the name of  this item ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
