<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total</name>
  <uuid>77ffa61a-ed4b-4b87-84b2-9d126109019e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;
-- Total of my basket  
for each item in the items of 'my shopping' : 
	- set decision to decision + the price of this item * the quantity of this item ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
