<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Règle conseil du jour</name>
  <uuid>06a49e4b-b6a7-4813-8838-76e529a17d4d</uuid>
  <documentation><![CDATA[Construit le conseil du jour à partir du nom et du conseil météo.]]></documentation>
  <locale>fr_FR</locale>
  <definition><![CDATA[si 
     Nom est défini alors 
affecter à décision "Bonjour " + Nom + "! " + 'Conseil lié aux prévisions' ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
