<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f3fcab78-5428-4076-92ce-eeaf615d404d</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión "Lo sentimos, no tenemos suficiente información para crear una recomendación." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
