<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>regla de recomendación</name>
  <uuid>4d117ba4-6e55-4322-9c49-968f4afdfc23</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[si
    Nombre está definido
entonces
    asignar a decisión "¡Hola! " + Nombre + "! " + 'Recomendación meteorológica' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
