<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Init</name>
  <uuid>2c5ef62f-bec1-4469-90af-c96c1906e2f5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ set  decision to { bad quality , what I expect } ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
