<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total</name>
  <uuid>24067755-d370-42de-83d4-12e2d1c47958</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión 0 ;
  -- Total de mi canasta ttttt
  para cada elemento en los elementos de 'mis compras' : 
	-definir decision como decisión + el precio de este elemento * la cantidad de este elemento; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
