<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Init</name>
  <uuid>04801c1f-0c34-4dff-8cfb-0ad815432003</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[  asignar a decisión { mala calidad , lo que esperaba }  ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
