<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Nombre</name>
  <uuid>870933f5-2709-4f45-a1f7-974bfb8e7ec1</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[para cada elemento ,  en  los elementos  de 'mis compras' 
imprimir   el nombre de este elemento ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
