<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Règle alerte tempête</name>
  <uuid>a7e5f951-51bd-4e26-bb46-6e079e315c94</uuid>
  <documentation><![CDATA[Cette règle sert à alerter en cas de tempête]]></documentation>
  <locale>fr_FR</locale>
  <definition><![CDATA[si
   Alerte tempête 
alors
    affecter à décision "Il serait sage de rester à la maison. Il y a une alerte: une tempête est prévue" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
