<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0ce65196-2c48-4ba7-a6bc-fa6bffd198f8</uuid>
  <locale>de_DE</locale>
  <definition><![CDATA[setze Entscheidung auf "Wir haben leider nicht genug Informationen, um eine Empfehlung abzugeben." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
