<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name> regla de alerta de tormenta</name>
  <uuid>1054c21f-4dd5-4443-a4de-562683f3633b</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[si
    'Pronóstico del tiempo' es alerta de tormenta
entonces
    asignar a decisión "Sería prudente quedarse en casa. Hay una alerta de tormenta." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
